-- SoilType table
DROP TABLE IF EXISTS app_soiltype;
CREATE TABLE app_soiltype (
    id SERIAL PRIMARY KEY,
    mukey VARCHAR(100) DEFAULT NULL,
    areasym VARCHAR(100) DEFAULT NULL,
    spatial DOUBLE PRECISION DEFAULT NULL,
    musym VARCHAR(100) DEFAULT NULL,
    shp_lng DOUBLE PRECISION DEFAULT NULL,
    shap_ar DOUBLE PRECISION DEFAULT NULL,
    si_label VARCHAR(255) DEFAULT NULL,
    muname VARCHAR(255) DEFAULT NULL,
    drclssd VARCHAR(100) DEFAULT NULL,
    frphrtd VARCHAR(100) DEFAULT NULL,
    avg_rs_l DOUBLE PRECISION DEFAULT NULL,
    avg_rs_h DOUBLE PRECISION DEFAULT NULL,
    geometry geometry(MULTIPOLYGON, 3857) DEFAULT NULL
);
