DROP TABLE IF EXISTS taxlots;
CREATE TABLE s_taxlots_geom (
    ID BIGSERIAL PRIMARY KEY,
    ODF_FPD TEXT,
    AGENCY TEXT,
    ORZDESC TEXT,
    HUC12 TEXT,
    NAME TEXT,
    LEGAL_LABEL TEXT,
    MIN_ELEVATION FLOAT,
    MAX_ELEVATION FLOAT,
    SOURCE TEXT,
    MAP_TAXLOT TEXT,
    MAP_ID TEXT,
    COUNTY TEXT,
    GEOM GEOMETRY(MultiPolygon, 3857)
);
